apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-28T21:10:56Z"
  generation: 3
  labels:
    olm.deployment-spec-hash: 79d95d4b7d
    olm.owner: cluster-logging.v5.6.6
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: test-space
    operators.coreos.com/cluster-logging.test-space: ""
  name: cluster-logging-operator
  namespace: test-space
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: cluster-logging.v5.6.6
    uid: 7a2c5f23-b861-433d-b0f5-7e7df1feac05
  resourceVersion: "38802891"
  uid: 39502e10-47ce-4551-a89e-b167854acbc5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: cluster-logging-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alm-examples: |-
          [
            {
              "apiVersion": "logging.openshift.io/v1",
              "kind": "ClusterLogForwarder",
              "metadata": {
                "name": "instance",
                "namespace": "openshift-logging"
              },
              "spec": {
                "outputs": [
                  {
                    "name": "remote-elasticsearch",
                    "secret": {
                      "name": "elasticsearch"
                    },
                    "type": "elasticsearch",
                    "url": "remote.example.org:9200"
                  }
                ],
                "pipelines": [
                  {
                    "inputRefs": [
                      "application",
                      "audit",
                      "infrastructure"
                    ],
                    "name": "enable-default-log-store",
                    "outputRefs": [
                      "default"
                    ]
                  },
                  {
                    "inputRefs": [
                      "application"
                    ],
                    "name": "forward-to-remote",
                    "outputRefs": [
                      "remote-elasticsearch"
                    ]
                  }
                ]
              }
            },
            {
              "apiVersion": "logging.openshift.io/v1",
              "kind": "ClusterLogging",
              "metadata": {
                "name": "instance",
                "namespace": "openshift-logging"
              },
              "spec": {
                "collection": {
                  "type": "fluentd"
                },
                "logStore": {
                  "elasticsearch": {
                    "nodeCount": 3,
                    "redundancyPolicy": "SingleRedundancy",
                    "resources": {
                      "requests": {
                        "memory": "2Gi"
                      }
                    },
                    "storage": {
                      "size": "200G",
                      "storageClassName": "gp2"
                    }
                  },
                  "retentionPolicy": {
                    "application": {
                      "maxAge": "7d"
                    }
                  },
                  "type": "elasticsearch"
                },
                "managementState": "Managed",
                "visualization": {
                  "kibana": {
                    "replicas": 1
                  },
                  "type": "kibana"
                }
              }
            }
          ]
        capabilities: Seamless Upgrades
        categories: OpenShift Optional, Logging & Tracing
        certified: "false"
        console.openshift.io/plugins: '["logging-view-plugin"]'
        containerImage: registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator@sha256:7dd6532c29cfa9a41b51b0d7b38753b42c1978a8535efaf706188376a3def7fd
        createdAt: "2018-08-01T08:00:00Z"
        description: The Red Hat OpenShift Logging Operator for OCP provides a means
          for configuring and managing your aggregated logging stack.
        kubectl.kubernetes.io/default-container: cluster-logging-operator
        olm.operatorGroup: test-space-lj47g
        olm.operatorNamespace: test-space
        olm.skipRange: '>=5.4.0-0 <5.6.6'
        olm.targetNamespaces: test-space
        operatorframework.io/cluster-monitoring: "true"
        operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"logging.openshift.io","kind":"ClusterLogForwarder","version":"v1"}},{"type":"olm.gvk","value":{"group":"logging.openshift.io","kind":"ClusterLogging","version":"v1"}},{"type":"olm.maxOpenShiftVersion","value":4.14},{"type":"olm.package","value":{"packageName":"cluster-logging","version":"5.6.6"}}]}'
        operatorframework.io/suggested-namespace: openshift-logging
        operators.openshift.io/infrastructure-features: '["disconnected","proxy-aware"]'
        operators.openshift.io/valid-subscription: '["OpenShift Kubernetes Engine",
          "OpenShift Container Platform", "OpenShift Platform Plus"]'
        operators.operatorframework.io/builder: operator-sdk-unknown
        operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
        support: AOS Logging (team-logging@redhat.com)
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      creationTimestamp: null
      labels:
        name: cluster-logging-operator
    spec:
      containers:
      - command:
        - cluster-logging-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: cluster-logging-operator
        - name: RELATED_IMAGE_VECTOR
          value: registry.redhat.io/openshift-logging/vector-rhel8@sha256:28186a12ae3f44767bbfdda5451cfd43ecedcc6c33e8dab98200297cde37b541
        - name: RELATED_IMAGE_FLUENTD
          value: registry.redhat.io/openshift-logging/fluentd-rhel8@sha256:c37c20400b8c097acfb894a6916575a1c2178acb10c779ecd7bccf8902af047d
        - name: RELATED_IMAGE_LOG_FILE_METRIC_EXPORTER
          value: registry.redhat.io/openshift-logging/log-file-metric-exporter-rhel8@sha256:a4ed549cc60e654ee1298a874c24f05ee0488ea550cbfdd243f013cc215f929e
        - name: RELATED_IMAGE_LOGGING_CONSOLE_PLUGIN
          value: registry.redhat.io/openshift-logging/logging-view-plugin-rhel8@sha256:4c577067c4c0e8819dccc639a961d6067459028c7866c554de3dcfa45cbdae5d
        - name: OPERATOR_CONDITION_NAME
          value: cluster-logging.v5.6.6
        image: registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator@sha256:7dd6532c29cfa9a41b51b0d7b38753b42c1978a8535efaf706188376a3def7fd
        imagePullPolicy: IfNotPresent
        name: cluster-logging-operator
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: cluster-logging-operator
      serviceAccountName: cluster-logging-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-05-28T21:10:56Z"
    lastUpdateTime: "2023-05-28T21:11:05Z"
    message: ReplicaSet "cluster-logging-operator-5467cdb784" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-28T21:13:09Z"
    lastUpdateTime: "2023-05-28T21:13:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
