apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1682596733
    service.beta.openshift.io/serving-cert-secret-name: elasticsearch-operator-metrics
    service.beta.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1682596733
  creationTimestamp: "2023-05-28T21:03:47Z"
  labels:
    name: elasticsearch-operator
    operators.coreos.com/elasticsearch-operator.test-space: ""
  name: elasticsearch-operator-metrics
  namespace: test-space
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: elasticsearch-operator.v5.6.6
    uid: e5635ab2-85a8-4475-a84b-361f746a1591
  resourceVersion: "38796271"
  uid: 9099c24c-5068-4c4c-bb2a-acf08611f371
spec:
  clusterIP: 172.30.176.142
  clusterIPs:
  - 172.30.176.142
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: elasticsearch-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
