apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-05-28T20:51:05Z"
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
    operators.coreos.com/opentelemetry-operator.test-space: ""
  name: opentelemetry-operator-controller-manager-metrics-service
  namespace: test-space
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: opentelemetry-operator.v0.77.0
    uid: b8cedac8-22b5-475f-9547-4057c9c215f4
  resourceVersion: "38787681"
  uid: 8078e3a4-57cc-4252-a715-9185e67a428a
spec:
  clusterIP: 172.30.240.122
  clusterIPs:
  - 172.30.240.122
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
